config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tools#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "pages/home", to: "pages#home"
  # get "pages/:id/home", to: "pages#filter"

  resources :tools do
    resources :bookings, only: %i[new create show destroy edit update]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :tool
  validates :start_date, presence: true, comparison: { greater_than_or_equal_to: Date.today}

  validates :end_date, presence: true, comparison: { greater_than: :start_date}

  enum status: [ :pending, :rejected, :accepted ]

  #private

  # def  start_date_after_today
  #   if Date.today.strftime("%Y-%m-%d") <= :start_date
  #     errors.add(:start_date, "must be after today")
  #   end
  # end

end

app/models/tool.rb
class Tool < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  CATEGORY = %w(professional beginners)
  SIZE = %w(small heavy voluminous)
  validates :category, inclusion: { in: CATEGORY }
  validates :size, inclusion: {in: SIZE }
  validates :name, :description, :image, :category, :size, presence: true

  pg_search_scope :search_by_name_and_description,
                  against: [:name, :description],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tools, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :first_name, :last_name, :email, :address, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validates_length_of :first_name, :last_name, maximum: 150, minimum: 3
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @tool = Tool.find(params[:tool_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @user = current_user
    @tool = Tool.find(params[:tool_id])
    @booking.tool = @tool
    @booking.user = @user
    respond_to do |format|
      if @booking.save
        format.html { redirect_to new_tool_booking(@tool), notice: "Booking was successfully created." }
        format.json
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json
      end
    end
  end



  def show
    @bookings.all
  end

  def destroy
    @booking = Booking.find(params[:id])
    @user = Tool.find(@booking.tool.id)
    @booking.destroy

    redirect_to
  end
  private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @user = current_user
    @tools = current_user.tools
    @tool = Tool.new
    @bookings = current_user.bookings
    @booking = Booking.new
    if params[:tool]
      @tool_id = params[:tool]
      @select_tool = Tool.find(@tool_id)
      @filter_booking = @select_tool.user.bookings.where(tool_id: @select_tool.id)[0]
      @select_booking = Booking.find(@filter_booking.id)
    else
      nil
    end
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_tool, only: %i[show edit update destroy]

  def new
  end

  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to tool_path(@tool), notice: "Tool was successfully created." }
        format.json
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json
      end
    end
  end

  def show
  end

  def index
    name_search = params.dig(:search, :search_by_name_and_description)
    @tools = if name_search.present?
              if Tool.search_by_name_and_description(name_search).count.zero?
                redirect_to tools_path(nothing: "nothing found")
              else
                Tool.search_by_name_and_description(name_search)
              end
             else
               Tool.all
             end
    @tool = Tool.new
    @booking = Booking.new
  end

  def update
    if @tool.update(tool_params)
      redirect_to @tool, notice: "Tool was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end



  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :description, :image, :size, :category, :price, :availability)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_edit.html.erb
 <div>
  <%= simple_form_for [@select_tool, @select_booking] do |f| %>

    <div class="form-inputs">
     <%= f.input :start_date,
      as: :string,
      input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :end_date,
        as: :string,
       input_html: { data: { controller: "datepicker" } } %>

        <div class="form-actions">
        <%= f.button :submit, class: "btn btn-danger btn-block border border-dark rounded-pill" %>
       </div>
    </div>
 <% end %>
 </div>

app/views/bookings/_editform.html.erb
<%= form_tag pages_home_path, method: 'get' do %>
  <%= select_tag :tool, options_from_collection_for_select(@tools, "id", "name") %>
  <%= submit_tag 'Filter' %>
<% end %>

app/views/bookings/_form.html.erb
<div>
  <p>Book your <%= tool.name %></p>
  <%= simple_form_for([tool, @booking], data: {
                      insert_in_list_target: "form",
                      action: "submit->insert-in-list#send" }) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :start_date,
      as: :string,
      input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :end_date,
      as: :string,
      input_html: { data: { controller: "datepicker" } } %>


      <div class="form-actions d-flex align-items-center justify-content-center">
        <%= f.button :submit, class: "btn btn-danger btn-block border border-dark rounded-pill" %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>
<%= render "bookings/form", tool: params[:tool_id], booking: @booking %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentATool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>


  <body>
    <div class="marie">
    <%= render "shared/navbar" if (current_user) %>
    <%= render "shared/flashes" %>
    <%= yield %>

  </div>
  </body>
</html>

app/views/pages/_card.html.erb
<div class="container">
<div class="text-center">
  <div class="banner">
    <%= image_tag('tool.jpg') %>

    <h3> hhxxxxxxxxxx </h3>



    <h1> xxxxxxxfggfgafgfgd0 years in the market </h1>

    <a class="btn btn-ghost" href="#">Log in</a>
    <a class="btn btn-ghost" href="#">Sig up</a>
  </div>
  </div>


  <div class="cards mt-5">
    <div class="card-category">
      <%= image_tag('drill.jpg') %>
    </div>

    <div class="card-category">
      <%= image_tag('chainsaw.jpg') %>
    </div>

    <div class="card-category">
      <%= image_tag('hammer.jpg') %>
    </div>

    <div class="card-category">
      <%= image_tag('box.jpg') %>
    </div>
  </div>

  <div class="d-flex justify-content-between my-4 align-items-center">
   <h2> Mobile version </h2>
    <%= image_tag('flag.jpg', id: 'flags') %>
  </div>
</div>








<%# <img src="images/Felix_cat.jpg" alt="marcel" style="width: 1400px; height: 220px"> %>

app/views/pages/home.html.erb
<div class="container mt-5" >
  <div class="d-inline-flex justify-content-between align-items">
    <h1 class="mt-2">Hello <%= @user.first_name %>!</h1>
    <%= image_tag "https://kitt.lewagon.com/placeholder/users/emmvs", style: "border-radius:50%; border-style: groove solid; border-color: black; width:60px; margin-left: 25px;"%>
  </div>
  <div class="mt-4">
    <div class="card">
      <div class="card-header d-inline-flex justify-content-between align-items-center">
        <h3 class="m-0">Your Info</h3>
        <div data-controller="toggle">
        <button class="btn btn-danger btn-block border border-dark rounded-pill" data-action="click->toggle#edit">Edit my infos</button>
          <div data-toggle-target="profileEdit" class="d-none">
           <%= render "devise/registrations/edit", resource_name: current_user, resource: current_user %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p><strong>First Name:</strong> <%= @user.first_name %></p>
        <p><strong>Last Name:</strong> <%= @user.last_name %></p>
        <p><strong>Address:</strong> <%= @user.address %></p>
        <p><strong>Password:</strong> <%= @user.password %></p>
      </div>
    </div>
  </div>

  <div class="mt-4">
    <div class="card">
      <div class="card-header d-inline-flex justify-content-between align-items-center">
        <h3 class="m-0" id="booking">Your Bookings</h3>
        <div data-controller="toggle">
        <button class="btn btn-danger btn-block border border-dark rounded-pill" data-action="click->toggle#editBooking">Edit my bookings</button>
          <div data-toggle-target="bookingEdit" class="d-none">
           <%= render "bookings/editform", user: current_user %>
          </div>
        </div>
      </div>
      <div class="card-body" data-insert-in-list-target="items" id="bookings">
          <% @user.bookings.each do |booking| %>
            <div class="booking-container">
              <%# <%= image_tag "tool-1.jpg", alt: "", class: "priscila"%>
              <div class="shit">
                <p><strong>Start Date:</strong> <%= booking.start_date.time.strftime("%d.%m.%Y") %></p>
                <p><strong>End Date:</strong> <%= booking.end_date.time.strftime("%d.%m.%Y") %></p>
                <p><strong>User:</strong> <%= booking.user.first_name %></p>
                <p ><strong>Tool:</strong> <%= booking.tool.name %></p>
                <p ><strong>Price:</strong> <%= booking.tool.price %> $</p>
              </div>

            <% if @tool_id %>
            <%= render "bookings/edit", select_tool: @select_tool, select_booking: @select_booking %>
            <% end %>
          <% end %>
         </div>
      </div>
    </div>
  </div>

  <div class="mt-4">
    <div class="card" >
      <div class="card-header d-inline-flex justify-content-between align-items-center">
        <h3 class="m-0" id="tool" data-controller="insert-in-list">Your Tools</h3>
        <div data-controller="toggle">
          <button class="btn btn-danger btn-block border border-dark rounded-pill" data-action="click->toggle#fire">Add a New Tool</button>
          <div data-toggle-target="togglableElement" class="d-none">
            <%= render "tools/form", tool: @tool %>
          </div>
        </div>
      </div>
      <div class="card-body" class= "mb-5" data-insert-in-list-target="items" id="tools">
        <% @user.tools.each do |tool|  %>
            <%# <img src="<%= asset_path(tool.image) %>
          <p><strong>Description:</strong> <%= tool.description  %></p>
          <p><strong>Category:</strong> <%= tool.category %></p>
          <p><strong>Size:</strong> <%= tool.size %></p>
          <p><strong>Price:</strong> <%= tool.price %></p>
          <p><strong>Availability:</strong> <%= tool.availability %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Schlaegel_und_Eisen_nach_DIN_21800.svg/800px-Schlaegel_und_Eisen_nach_DIN_21800.svg.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Profile", pages_home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bookings", "#{pages_home_path}#booking", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/emmvs", class: "avatar", style: "border-style: solid groove; border-color: black", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "See my tools", "#{pages_home_path}#tool", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_tool_card.html.erb
<div class="card-trip-infos ">
  <div class="card-trip-description">
    <p><strong><%= tool.description %></strong></p>
  </div>
  <div class="card-trip-details">
    <div class="detail">
      <p><strong>Owner:</strong> <%= tool.user.first_name %></p>
    </div>
    <div class="detail">
      <p><strong>Availability:</strong> <%= tool.availability ? "Available" : "Unavailable" %></p>
    </div>
    <div class="detail">
      <p><strong>Cost:</strong> <%= tool.price %></p>
    </div>
    <div class="detail">
      <p><strong>Size:</strong> <%= tool.size %></p>
    </div>
    <div class="detail">
      <p><strong>Category:</strong> <%= tool.category %></p>
    </div>
  </div>
</div>

app/views/tools/_cards.html.erb
<div class="card-product-infos">

<%= @tool.name %>
<%= @tool.user.first_name %>
</div>

app/views/tools/_error.html.erb
<p>Sorry, no results found!</p>

app/views/tools/_form.html.erb
<%= simple_form_for(tool, data: {
                              insert_in_list_target: "form",
                              action: "submit->insert-in-list#send" }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
   <%= f.input :image, as: :file %>
      <%= f.input :category, collection: ['professional', 'beginners']%>
      <%= f.input :size, collection: ['small', 'heavy', 'voluminous']%>
      <%= f.input :price %>
      <%= f.input :availability, collection: ['yes', 'no'] %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-danger btn-block border border-dark rounded-pill" %>
  </div>
   </div>
<% end %>

app/views/tools/_search.html.erb
<div class="d-inline-flex">
<%= simple_form_for(:search, method: :get, url: tools_path, html: {  }) do |f| %>
  <div class="row ">
    <div class="col-md-8">
      <%= f.error_notification %>
      <%= f.input_field :search_by_name_and_description,
                    class: "form-control search-input",
                    placeholder: "Search by tool name" %>
    </div>
    <div class="col-md-4 ml-0">
      <%= f.button :submit, "Search", class:"md-form mt-0 btn btn-danger btn-block border border-dark rounded-pill" %>
    </div>
  </div>
<% end %>
</div>

app/views/tools/_tools-cards.html.erb
 
<body>

<div class="tool class"></div>
<h1 class="text-center">Rent a tool</h1>


<form action="/create" method="post">
<input type="text" placeholder=" Find a tool...." name="search">
<button class=" btn btn-primary" lenght="">Search</button>
</form>


<div class="mb-3">
<input type="submit" value="Sign up" name="submit" class="submit" />
</div>


<%="Recently rented"%>
<%= image_tag "/app/assets/images/Drill.jpeg" %>
<body>

<%# <label>Enter the Username</label> %>
<%# <input type="text" name="username" />
<label>Enter the Password</label>
<input type="password" name="password" /> %>

<%# <input type="submit" value="Sign up" name="submit" class="submit" />
<input type="submit" value="Login" name="submit" class="submit" /> %>

app/views/tools/create.html.erb
<h1>Tools#create</h1>
<p>Find me in app/views/tools/create.html.erb</p>

app/views/tools/index.html.erb
<div class="container full-viewwidth">
  <% if !user_signed_in? %>
    <div class="banner" style="background-image: linear-gradient(rgba(206,18,18,0.4),rgba(122,21,21,0.4)), url(<%= asset_path('tool-5.jpg')%>)">
      <div class="tagline">
        <%= image_tag('https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Schlaegel_und_Eisen_nach_DIN_21800.svg/800px-Schlaegel_und_Eisen_nach_DIN_21800.svg.png', resize: "100", size:"200") %>
        <h1> Rent a Tool </h1>
        <p> Your Center specialized in Tool Rental Service for over 20 years in the market </p>
        <%= link_to "Join the community", new_user_registration_path, class: "btn btn-danger btn-block border border-dark rounded-pill" %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-danger btn-block border border-dark rounded-pill" %>
      </div>
    </div>
  <% end %>

    <div class="mt-4 text-center searchbar">
      <%= render "search" %>
    </div>

    <% if params[:nothing].present? %>
      <div class="error-container">
        <div class="message">
          <%= render "error" %>
        </div>
      </div>
    <% end %>
  <h3 class="mt-5 mb-0 d-flex" style="margin-left: 90px;">Latest tools</h3>
    <div class="cards mt-5" data-insert-in-list-target="items">
      <% @tools.each do |tool|%>
        <div class="card-trip mt-5" data-controller="toggle">
          <h2><%= tool.name %></h2>
          <img src="<%= asset_path(tool.image) %>" alt="">
          <div class="d-flex align-items-center flex-column my-2">
            <div class="more-info d-flex align-items-center flex-column">
              <button class="btn btn-danger btn-block border border-dark rounded-pill" data-action="click->toggle#tool">More infos</button>
              <div data-toggle-target="toolElement" class="d-none">
                <%= render "shared/tool_card", tool: tool %>
              </div>
            </div>
            <div class="form-toggle d-flex align-items-center flex-column my-2">
              <button class="btn btn-danger btn-block border border-dark rounded-pill" data-action="click->toggle#booking">Request a new booking</button>
              <div data-toggle-target="bookingElement" class="d-none p-2 ">
                <%= render "bookings/form", tool: tool, booking: @booking %>
                <%# <%= link_to "Request a booking",  new_tool_booking_path(tool), class: "btn btn-primary" %>
              </div>
            </div>
           </div>
        </div>
      <% end %>

    </div>
</div>

app/views/tools/new.html.erb
<%# <h1>Tools#new</h1>
<p>Find me in app/views/tools/new.html.erb</p> %>

app/views/tools/show.html.erb
<h1>Tools#show</h1>
<p>Find me in app/views/tools/show.html.erb</p>

<%= @tool.name %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>